
export const SELECTED_FILE = 'SELECTED_FILE';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILURE = 'UPLOAD_FILE_FAILURE';
export const REMOVE_FILE = 'REMOVE_FILE';

export const GET_FILES = 'GET_FILES';
export const GET_FILES_SUCCESS = 'GET_FILES_SUCCESS';
export const GET_FILES_FAILURE = 'GET_FILES_FAILURE';

export const DELETE_FILE = 'DELETE_FILE';
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';
export const DELETE_FILE_FAILURE = 'DELETE_FILE_FAILURE';
export const ASK_FOR_DELETING_FILE = 'ASK_FOR_DELETING_FILE';
export const SHOW_CONFOIRMATION_DIALOG = 'SHOW_CONFOIRMATION_DIALOG';
export const CLOSE_MODAL_CONFIRMATION = 'CLOSE_MODAL_CONFIRMATION';