export const GOTO_NEWS_HOME = 'GOTO_HOME_NEWS';
export const GOTO_NEWS_DETAIL = 'GOTO_NEWS_DETAIL';
export const GOTO_FILES = 'GOTO_FILES';
export const HANDLE_FILES_ROUTE = 'HANDLE_FILES_ROUTE';
export const GOTO_HOME = 'GOTO_HOME';
export const HANDLE_HOME_ROUTE = 'HANDLE_HOME_ROUTE';
export const HANDLE_NEWS_HOME_ROUTE = 'HANDLE_NEWS_HOME_ROUTE';
